Fix the some unintended changes to peer-id
libp2p/js-libp2p-interfaces pull request #126
Opened 2021-12-25 02:28 UTC by nazarhussain

In the PR https://github.com/libp2p/js-libp2p-interfaces/pull/107  the `PeerId` interface was introduced. Later in the PR https://github.com/libp2p/js-libp2p-interfaces/pull/111/ that was refactored and some intentional changes introduced. 

The `privKey` and `pubKey` both can be undefined depending on the data, more details can be found in the PR https://github.com/libp2p/js-peer-id/pull/150.

The `PeerId` object can be created with the following scenarios: 

1. `new` in that case both keys are optional 
2. `PeerId.create` in that case if provided input is valid than both keys exists 
3. `PeerId.createFromBytes`, `PeerId.createFromB58String`, `PeerId.createFromHexString`, `PeerId.createFromCID`  in these cases public key _can_ be decoded but private key don't exists 
4. `PeerId.createFromPubKey` in that case public key exists but not private 
5. `PeerId.createFromPrivKey` in that case both keys exist
6. `PeerId.createFromJSON` in that case both keys exist 
7. `PeerId.createFromProtobuf` in that case both keys exist

Considering all the above cases, both `privKey` and `pubKey` were initially set was set to have `undefined`  values. Seems the change in refactoring PR #111 was made unintended.

2021-12-25 08:33 UTC, achingbrain commented
TLDR: please use the v2.x.x release for the time being, tagged `latest` on npm - PRs can target the `release/v2.x.x` branch.

----

Longer version:

The typescript version of libp2p-interfaces is trying to take the interface definitions in a new direction.  For peer id, please see the changes in https://github.com/libp2p/js-libp2p-interfaces/pull/117 - it makes peer ids essentially a place to store some `Uint8Array`s which you can then use to do encryption rather than pulling in `libp2p-crypto` by default.  This is to allow using peer id datatypes in lightweight clients like `ipfs-http-client` instead of having everything as opaque strings.

It's all a bit in flux and will be until https://github.com/libp2p/js-libp2p/issues/1021 lands.

2021-12-27 19:28 UTC, nazarhussain commented
@achingbrain  Please review.

2022-01-01 07:31 UTC, achingbrain requested changes
Good catch - thanks! Just a few changes needed in order for the tests to not cause unhanded promise rejections if they fail.

2022-01-01 07:31 UTC, achingbrain commented on packages/compliance-tests/src/peer-id/index.js
> +        expect(factory.createFromJSON({
You need to await on or return the promise returned when using `eventually`:

```suggestion
        await expect(factory.createFromJSON({
```

2022-01-01 07:31 UTC, achingbrain commented on packages/compliance-tests/src/peer-id/index.js
> +        expect(factory.createFromJSON({
You need to await on or return the promise returned when using `eventually`:

```suggestion
        await expect(factory.createFromJSON({
```

2022-01-01 07:31 UTC, achingbrain commented on packages/compliance-tests/src/peer-id/index.js
> +        expect(factory.createFromJSON('hello world')).eventually.be.rejectedWith(/invalid id/)
You need to await on or return the promise returned when using `eventually`:

```suggestion
        await expect(factory.createFromJSON('hello world')).eventually.be.rejectedWith(/invalid id/)
```

2022-01-02 07:48 UTC, merged