Close read write
libp2p/js-libp2p-interfaces pull request #92
Opened 2021-04-19 20:22 UTC by filoozom

See https://github.com/libp2p/js-libp2p-mplex/pull/122

2021-04-20 09:18 UTC, vasco-santos reviewed
This looks good to me. Can you just rebase this with origin master so that I can double test these branches in libp2p before a release?

2021-04-21 13:35 UTC, vasco-santos requested changes

2021-04-21 14:05 UTC, filoozom commented on src/stream-muxer/tests/close-test.js
> +        // Immediate close for write
Ah damn, I didn't pay attention, pushed a commit to fix this.

2021-05-31 14:27 UTC, lidel commented
(note from triage) blocked until we decide how to handle aborts in browser/node
Closing this PR as the solution is most likely elsewhere (properly cascade close event), but thank you for opening this to highlight the problem @filoozom

2021-05-31 14:27 UTC, closed without merging